AWSTemplateFormatVersion: 2010-09-09
Description: BooksDemo RestApi block

Parameters:
  Environment:
    Description: Environment Name
    Type: String
  SQSQueueArn:
    Description: SQS queue Arn
    Type: String

Resources:
  booksDemoDynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: bookId
          AttributeType: S
      KeySchema:
        - AttributeName: bookId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub booksdemo-${Environment}

  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole 
      Policies:
        - PolicyName: "dynamodb-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !GetAtt booksDemoDynamodbTable.Arn
        - PolicyName: "sqs-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "${SQSQueueArn}"
        - PolicyName: "codedeploy-bucket-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - s3:GetObject,
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource: arn:aws:s3:::*/CodeDeploy/*

  Ec2SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: [!Ref iamRole]

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  BooksDemoEC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
        ResourceSignal:
          Count: '1'
          Timeout: PT5M
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              ruby: []
          files:
            "/home/ec2-user/install":
              source:
                Fn::Join:
                - ''
                - - https://aws-codedeploy-
                  - Ref: AWS::Region
                  - ".s3.amazonaws.com/latest/install"
              mode: '000755'
          commands:
            00-install-agent:
              command: "./install auto"
              cwd: "/home/ec2-user/"
            01-cfn-signal:
              command:
                Fn::Join:
                - ''
                - - "/opt/aws/bin/cfn-signal -e 0 --stack "
                  - Ref: AWS::StackName
                  - " --resource "
                  - !Sub BooksDemoRest${Environment}
                  - " --region "
                  - Ref: AWS::Region
    Properties:
      ImageId: ami-026b57f3c383c2eec
      InstanceType: t2.micro
      Monitoring: false
      IamInstanceProfile: !Ref Ec2SsmInstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: !Sub BooksDemoRest${Environment}
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - 'yum -y update

              '
            - 'yum -y install cfn-bootstrap

              '
            - "/opt/aws/bin/cfn-init -v"
            - " --stack "
            - Ref: AWS::StackName
            - " --resource SampleLinuxInstance"
            - " --region "
            - Ref: AWS::Region
            - "\n"
      Tags:
        - Key: Name
          Value: !Sub BooksDemo${Environment}

Outputs:
  InstanceId:
    Description: InstanceId
    Value: !Ref BooksDemoEC2Instance
  PublicDNS:
    Description: Public DNS Name
    Value: !GetAtt
            - BooksDemoEC2Instance
            - PublicDnsName
  PublicIP:
    Description: Public IP Address of EC2 instance
    Value: !GetAtt
            - BooksDemoEC2Instance
            - PublicIp
    