AWSTemplateFormatVersion: 2010-09-09
Description: BooksDemo RestApi block

Parameters:
  Environment:
    Description: Environment Name
    Type: String
  SQSQueueArn:
    Description: SQS queue Arn
    Type: String

Resources:
  booksDemoDynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: bookId
          AttributeType: S
      KeySchema:
        - AttributeName: bookId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub booksdemo-${Environment}

  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole 
      Policies:
        - PolicyName: "dynamodb-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !GetAtt booksDemoDynamodbTable.Arn
        - PolicyName: "sqs-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "${SQSQueueArn}"

  Ec2SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: [!Ref iamRole]

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  BooksDemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08c40ec9ead489470
      InstanceType: t2.micro
      Monitoring: false
      IamInstanceProfile: !Ref Ec2SsmInstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: !Sub BooksDemoRest${Environment}
      Tags:
        - Key: Name
          Value: !Sub BooksDemo${Environment}

Outputs:
  InstanceId:
    Description: InstanceId
    Value: !Ref BooksDemoEC2Instance
  PublicDNS:
    Description: Public DNS Name
    Value: !GetAtt
            - BooksDemoEC2Instance
            - PublicDnsName
  PublicIP:
    Description: Public IP Address of EC2 instance
    Value: !GetAtt
            - BooksDemoEC2Instance
            - PublicIp
    