AWSTemplateFormatVersion: 2010-09-09
Description: BooksDemo S3 log 

Parameters:
  Environment:
    Description: Environment Name for SQS
    Type: String

Resources:
  booksDemoS3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub books-demo-logs-${Environment}

Outputs:
  S3URL: 
    Description: "URL of new Amazon S3"
    Value: 
      Ref: booksDemoS3
    Export:
      Name: !Sub booksDemoS3Url${Environment}
  S3ARN: 
    Description: "ARN of new Amazon S3"
    Value: 
      Fn::GetAtt: 
        - booksDemoS3
        - Arn
    Export:
      Name: !Sub booksDemoS3Arn${Environment}
  S3Name:
    Description: "Name of new Amazon S3"
    Value:
      Fn::GetAtt: 
        - booksDemoS3
        - BucketName
    Export:
      Name: !Sub booksDemoS3Name${Environment}