AWSTemplateFormatVersion: 2010-09-09
Description: BooksDemo 

Parameters:
  Environment:
    Description: Environment Name for SQS
    Type: String

Resources:
  booksDemoSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub BooksDemo${Environment}.fifo
      DelaySeconds: 10
      MessageRetentionPeriod: 100
      VisibilityTimeout: 500 
      FifoQueue:  true

Outputs:
  QueueURL: 
    Description: "URL of new Amazon SQS Queue"
    Value: 
      Ref: booksDemoSQS
    Export:
      Name: !Sub booksDemoSQSUrl${Environment}
  QueueARN: 
    Description: "ARN of new AmazonSQS Queue"
    Value: 
      Fn::GetAtt: 
        - booksDemoSQS
        - Arn
    Export:
      Name: !Sub booksDemoSQSArn${Environment}
  QueueName: 
    Description: "Name of new Amazon SQS Queue"
    Value: 
      Fn::GetAtt: 
        - booksDemoSQS
        - QueueName
    Export:
      Name: !Sub booksDemoSQSName${Environment}
