name: CloudFormation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Make artifacts directory
      run: mkdir artifact

    - name: Copy SQS CloudFormation Template
      run: cp ./SQSCloudFormation.yaml ./artifact/SQSCloudFormation.yaml

    - name: Copy RestApi CloudFormation Template
      run: cp ./RestApiCloudFormation.yaml ./artifact/RestApiCloudFormation.yaml

    - uses: actions/upload-artifact@v3
      with:
        name: rest
        path: ./artifact

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  test-deploy:
    runs-on: ubuntu-latest
    environment: Test
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rest
          path: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy SQS to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sqs-block
          template: artifact/SQSCloudFormation.yaml
          parameter-overrides: "Environment=test"

      - name: Get outputs from the stack just created
        id: get-outputs
        run: >-
          echo "::set-output name=ECRURI::$(
            aws cloudformation \
            --region us-east-1 describe-stacks \
            --stack-name $(echo ${GITHUB_REF##*/}) \
            --query "Stacks[0].Outputs[0].OutputValue"
          )"

      - name: Deploy Rest to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rest-block
          template: artifact/RestApiCloudFormation.yaml
          parameter-overrides: "Environment=test,SQSQueueArn=${{ steps.get-outputs.outputs.QueueARN }}"