name: CloudFormation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Make artifacts directory
      run: mkdir artifact

    - name: Copy SQS CloudFormation Template
      run: cp ./SQSCloudFormation.yaml ./artifact/SQSCloudFormation.yaml

    - run: cp ./RestApiCloudFormation.yaml ./artifact/RestApiCloudFormation.yaml

    - run: cp ./S3CloudFormation.yaml ./artifact/S3CloudFormation.yaml

    - run: cp ./LogLambdaCloudFormation ./artifact/LogLambdaCloudFormation.yaml

    - uses: actions/upload-artifact@v3
      with:
        name: rest
        path: ./artifact

  test-deploy:
    runs-on: ubuntu-latest
    environment: Test
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rest
          path: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy SQS to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sqs-block
          template: artifact/SQSCloudFormation.yaml
          parameter-overrides: "Environment=test"
          no-fail-on-empty-changeset: "1"

      - name: Get outputs from the stack just created
        id: get-sqs-outputs
        run: >-
          echo "::set-output name=QueueName::$(
            aws cloudformation \
            --region us-east-1 describe-stacks \
            --stack-name sqs-block \
            --query "Stacks[0].Outputs[1].OutputValue"
          )"

      - name: Get outputs from the stack just created
        id: get-sqs-arn-outputs
        run: echo "::set-output name=QueueArn::arn:aws:sqs:us-east-1:*:${{ steps.get-sqs-outputs.outputs.QueueName }}"

      
      - name: Deploy Rest to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rest-block
          template: artifact/RestApiCloudFormation.yaml
          parameter-overrides: Environment=test,SQSQueueArn=${{ steps.get-sqs-arn-outputs.outputs.QueueArn }}
          no-fail-on-empty-changeset: "1"

      - name: Deploy S3 log bucket to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: log-block
          template: artifact/S3CloudFormation.yaml
          parameter-overrides: Environment=test

      - name: Get outputs from the stack just created
        id: get-s3-outputs
        run: >-
          echo "::set-output name=S3ARN::$(
            aws cloudformation \
            --region us-east-1 describe-stacks \
            --stack-name sqs-block \
            --query "Stacks[0].Outputs[0].OutputValue"
          )"

      - name: Get outputs from the stack just created
        id: get-s3-arn-outputs
        run: echo "::set-output name=QueueArn::arn:aws:sqs:us-east-1:*:${{ steps.get-s3-outputs.outputs.S3ARN }}"

        

      - name: Deploy log lambda to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: log-block
          template: artifact/LogLambdaCloudFormation.yaml
          parameter-overrides: Environment=test,SQSQueueArn=${{ steps.get-sqs-arn-outputs.outputs.QueueArn }}