name: SQSCloudFormation

on:
  push:
    branches: [ "master" ]
    paths:
      - "SQSCloudFormation.yaml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "SQSCloudFormation.yaml"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Make artifacts directory
      run: mkdir artifact

    - name: Copy RestApi CloudFormation Template
      run: cp ./SQSCloudFormation.yaml ./artifact/SQSCloudFormation.yaml

    - uses: actions/upload-artifact@v3
      with:
        name: rest
        path: ./artifact

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  test-deploy:
    runs-on: ubuntu-latest
    environment: Test
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rest
          path: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sqs-block
          template: artifact/SQSCloudFormation.yaml
          parameter-overrides: "Environment=test"

